apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 4
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 390403862591.dkr.ecr.us-east-1.amazonaws.com/jenkins-ci:latest
        ports:
        - containerPort: 80
